# Exclude all generated code
exclude_patterns:
- "server/openapi/"
- "server/internal/"
- "cli/openapi/"

plugins:
  rubocop:
    enabled: true
    checks:
      # Disable method length check for all go tests
      Rubocop/Metrics/MethodLength:
        Exclude:
          - "server/**/*_test.go"
