openapi: 3.0.0
info:
  version: 0.0.1
  title: Project X
  description: OpenAPI definition for project X endpoint and resources
paths:
  /tests:
    get:
      tags:
        - api
      summary: "Create new test"
      description: "get tests"
      operationId: getTests
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Test"
        500:
          description: "problem with creating test"
          # content:
          #   application/problem+json:
          #     schema:
          #       type: array
          #       items:
          #         $ref: "#/components/schemas/Problem"
    post:
      tags:
        - api
      summary: "Create new test"
      description: "Create new test action"
      operationId: createTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Test"
        500:
          description: "problem with creating test"
          # content:
          #   application/problem+json:
          #     schema:
          #       type: array
          #       items:
          #         $ref: "#/components/schemas/Problem"
  /tests/{testid}/run:
    post:
      tags:
        - api
      parameters:
        - in: path
          name: testid
          schema:
            type: string
          required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestRun"

  /tests/{testid}/results/{id}:
    get:
      tags:
        - api
      parameters:
        - in: path
          name: testid
          schema:
            type: string
          required: true
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Result"

  /tests/{id}/results:
    get:
      tags:
        - api
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Result"
  /test/{id}/assertions:
    get:
      tags:
        - api
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      operationId: getAssertions
      description: "Gets all assertions associated to the test"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Assertion"
    post:
      tags:
        - api
      description: ""
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      operationId: createAssertion
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Assertion"
      responses:
        "200":
          description: OK

components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: string
          description: ID
          readOnly: true
        name:
          type: string
        description:
          type: string
        serviceUnderTest:
          type: object
          properties:
            id:
              type: string
              description: ID
              readOnly: true
            url:
              type: string
              description: URL of the service under test
            auth:
              type: string
              description: authorization data for the request
        assertions:
          type: array
          items:
            $ref: "#/components/schemas/Assertion"
          description: Definition of assertions that are going to be made
        repeats:
          type: integer
    Assertion:
      type: object
      properties:
        id:
          type: string
          description: ID
          readOnly: true
        selector:
          description: Defines the scope where the sought property/ies is located
          type: string
        comparable:
          description: Defines the expected value of the property/ies
          type: string
        operator:
          description: |
            Defines how the value of sought property/ies should be compared
            For example lt (less then), gt (greater then), eq (equals), in (contains)
          type: string
        successful:
          type: boolean
    Result:
      type: object
      properties:
        id:
          type: string
          description: ID
          readOnly: true
        traceid:
          type: string
          description: trace ID
          readOnly: true
        successful:
          $ref: "#/components/schemas/Assertion"
        failed:
          $ref: "#/components/schemas/Assertion"
        createdAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
    Attribute:
      type: object
      properties:
        id:
          type: string
          description: ID
          readOnly: true
        key:
          type: string
        value:
          type: string
    TestRun:
      type: object
      properties:
        id:
          type: string
          description: ID
          readOnly: true
