name: build and test

# Cancel any pending or running workflow if the new one is triggered
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker metadata for Tracetest
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/tracetest
          tags: |
            type=match,pattern=v(.*)
            type=sha
          flavor: |
            latest=true
      - name: Build and push Tracetest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
